parameters:
#    site_message.example.class: Site\MessageBundle\Example

services:
#    site_message.example:
#        class: %site_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
