site_activities:
    pattern:  /
    defaults: { _controller: SiteActivityBundle:Activity:index }

site_activities_module:
    pattern:  /module/{id}
    defaults: { _controller: SiteActivityBundle:Activity:module }
    requirements:
        id: \d+

site_activities_module_registration:
    pattern:  /module/registration/{id}
    defaults: { _controller: SiteActivityBundle:Activity:moduleRegistration }
    requirements:
        id: \d+

site_activities_activity:
    pattern:  /activity/{id}
    defaults: { _controller: SiteActivityBundle:Activity:activity }
    requirements:
        id: \d+

site_activities_activity_registration:
    pattern:  /activity/registration/{id}
    defaults: { _controller: SiteActivityBundle:Activity:activityRegistration }
    requirements:
        id: \d+

site_activities_scale_show:
    pattern:  /activity/{id}/correction
    defaults: { _controller: SiteActivityBundle:Scale:show }
    requirements:
        id: \d+