parameters:
#    site_activity.example.class: Site\ActivityBundle\Example

services:
#    site_activity.example:
#        class: %site_activity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    site_activity.admin.module:
        class: Site\ActivityBundle\Admin\ModuleAdmin
        arguments: [~, Site\ActivityBundle\Entity\Module, SiteActivityBundle:ModuleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Modules, label: Module}
    site_activity.admin.activity:
        class: Site\ActivityBundle\Admin\ActivityAdmin
        arguments: [~, Site\ActivityBundle\Entity\Activity, SiteActivityBundle:ActivityAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Modules, label: Activity}
