parameters:
#    site_intra.example.class: Site\IntraBundle\Example

services:
#    site_intra.example:
#        class: %site_intra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
