root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: intra_index


site_activity:
    resource: "@SiteActivityBundle/Resources/config/routing.yml"
    prefix:   /activities


site_intra:
    resource: "@SiteIntraBundle/Resources/config/routing.yml"
    prefix:   /index


site_forum:
    resource: "@SiteForumBundle/Resources/config/routing.yml"
    prefix:   /forum


site_ticket:
    resource: "@SiteTicketBundle/Resources/config/routing.yml"
    prefix:   /tickets


site_directory:
    resource: "@SiteDirectoryBundle/Resources/config/routing.yml"
    prefix:   /directory


sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
