parameters:
#    site_ticket.example.class: Site\TicketBundle\Example

services:
    sonata.admin.ticket:
        class: Site\TicketBundle\Admin\TicketAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tickets", label: "ADMIN_HEADING_TICKETS" }
        arguments:
            - ~
            - Site\TicketBundle\Entity\TicketTicket
            - ~
    sonata.admin.message:
        class: Site\TicketBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tickets", label: "ADMIN_HEADING_MESSAGES" }
        arguments:
            - ~
            - Site\TicketBundle\Entity\TicketMessage
            - ~
