parameters:
#    site_forum.example.class: Site\ForumBundle\Example

services:
    sonata.admin.board:
        class: Site\ForumBundle\Admin\BoardAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "ADMIN_HEADING_BOARDS" }
        arguments:
            - ~
            - Site\ForumBundle\Entity\ForumBoard
            - ~
    sonata.admin.subboard:
        class: Site\ForumBundle\Admin\SubboardAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "ADMIN_HEADING_SUBBOARDS" }
        arguments:
            - ~
            - Site\ForumBundle\Entity\ForumSubboard
            - ~
    sonata.admin.thread:
        class: Site\ForumBundle\Admin\ThreadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "ADMIN_HEADING_THREADS" }
        arguments:
            - ~
            - Site\ForumBundle\Entity\ForumThread
            - ~
    sonata.admin.post:
        class: Site\ForumBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "ADMIN_HEADING_POSTS" }
        arguments:
            - ~
            - Site\ForumBundle\Entity\ForumPost
            - ~
    sonata.admin.comment:
        class: Site\ForumBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "ADMIN_HEADING_COMMENTS" }
        arguments:
            - ~
            - Site\ForumBundle\Entity\ForumComment
            - ~
